server:
  port: 8050
spring:
  application:
    name: zuul  # 应用名称，会在Eureka中显示
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/mongodb

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      #jpa:
    #show-sql: true
    #hibernate:
    #ddl-auto: update
eureka:
  client:
    fetch-registry: false   #从注册中心拉
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka


zuul:
  prefix: /api # 添加路由前缀
  strip-prefix: true
  routes:
    mongodb-provider: # 这里是路由id，不能随意写
      path: /mongodb/** # 这里是映射路径
      url: http://127.0.0.1:8010 # 映射路径对应的实际url地址
  #  shop-service: # 这里是路由id，不能随意写
      #   path: /providerShop/** # 这里是映射路径
    #   url: http://127.0.0.1:8089 # 映射路径对应的实际url地址



