server:
  port: 8010
spring:
  application:
    name: mongodb-provider # 应用名称，会在Eureka中显示
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/mongodb

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      #jpa:
      #show-sql: true
    #hibernate:
    #ddl-auto: update
eureka:
  client:
    fetch-registry: false   #从注册中心拉
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka


